## A McKinsey Data Science Hackathon

## Statement of Problem

“Beeep…Beeeep….Beeeep… Hooomans*, are you there?...”

This very strange transmission is coming from your narrowband radio signal receiver, pointed towards one of the farthest away galaxies. It’s early morning, you are sitting in your radio observatory high in the mountains.

For the last 10 years you’ve been a Chief Data Scientist in one of the best astrophysics research teams in the world. You are enjoying a quiet time with a cup of coffee and reviewing the data reports from last night, when this strange sound arrived. You almost spill your coffee in surprise. “Am I dreaming?” is your first thought as you move closer towards the speaker and listen…

“Beep…Beeeep….Beeeep… To all Hooomans who can hear us – we need your help”

You lean closer and grab a notebook and a pencil – you don’t really trust computers when it comes to such important tasks as taking notes from a radio transmission. You start recording everything that the strange voice from light years away is saying.

“… We need serious Data Science help and we know you Hooomans are the best at it…. We are an intergalactic species which have almost achieved singularity and the highest possible levels of development. We travel fast through space and explore other galaxies”

“The only essence that we consume is energy, measured in DSML units…Our populace is widespread and we live across many different star clusters and galaxies. What we need now is to optimize our well-being across all those galaxies… We have a lot of data but our сomputers and methods are too weak – we urgently need your data science knowledge to help us”

“Only two steps prevent us from achieving singularity

· To understand what makes us better off.

Our elders used the composite index to measure our well-being performance, but this knowledge has disappeared in the sands of time.

Use our data and train your model to predict this index with the highest possible level of certainty.

· To achieve the highest possible level of well-being through optimized allocation of additional energy

We have discovered the star of an unusually high energy of 50000 zillion DSML.

We have agreed between ourselves that 

· no one galaxy will consume more than 100 zillion DSML 

and 

· at least 10% of the total energy will be consumed by galaxies in need with existence expectancy index below 0,7.

Think of our galaxies as your “countries” (or how you call them??) and our population as citizens. We have similar healthcare and wellbeing characteristic as you, Hooomans”

“We are sending all the data to you right now. Let the data be with you, Hoomans… … …”

Transmission suddenly ends. You put your notebook and pencil away and start thinking. You really want to help this species optimize their well-being. You open up Python and upload the dataset from the narrowband radio signal receiver. It will be another great day at the observatory today.

————

probably intergalactic species meant to say “humans” here but we will never know for sure

Description Data Recieved
The solutions are evaluated on two criteria: predicted future Index values and allocated energy from a newly discovered star

1. Index predictions are evaluated using RMSE metric

2. Energy allocation is also evaluated using RMSE metric and has a set of known factors that need to be taken into account.

Every galaxy has a certain limited potential for improvement in the index described by the following function:

Potential for increase in the Index = -np.log(Index+0.01)+3

Likely index increase dependent on potential for improvement and on extra energy availability is described by the following function:

Likely increase in the Index = extra energy * Potential for increase in the Index **2 / 1000

There are also several constraints:

in total there are 50000 zillion DSML available for allocation and no galaxy at a point in time should be allocated more than 100 zillion DSML or less than 0 zillion DSML. Galaxies with low existence expectancy index below 0.7 should be allocated at least 10% of the total energy available in the foreseeable future

3. Leaderboard is based on a combined scaled metric:

80% prediction task RMSE + 20% optimization task RMSE * lambda where lambda is a normalizing factor

4. Leaderboard is 80% public and 20% private

5. The submission should be in the following format:

Variable
Index
pred
opt_pred

Description
Index: Unique index from the test dataset in the ascending order
pred: Prediction for the index on interest
opt_pred: Optimal energy allocation

## 1. Let's import pandas and numpy.

In [2]:
import numpy as np
import pandas as pd

## 2. Loading the datasets.

In [3]:
data_train = pd.read_csv('./Documents/prohack_dataset/train.csv') #train data
data_test = pd.read_csv('./Documents/prohack_dataset/test.csv') #test data
data_labels = data_train['y'] #selecting 'y' column from the train data to use as label
#galaxy_names = data_train.pop('galaxy')

In [4]:
data_train.head()

,galactic year,galaxy,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,...,"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII),y
0,990025,Large Magellanic Cloud (LMC),0.628657,63.125200,27109.234310,0.646039,8.240543,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.052590
1,990025,Camelopardalis B,0.818082,81.004994,30166.793958,0.852246,10.671823,4.742470,0.833624,0.467873,...,NaN,NaN,NaN,NaN,NaN,19.177926,NaN,22.785018,NaN,0.059868
2,990025,Virgo I,0.659443,59.570534,8441.707353,0.499762,8.840316,5.583973,0.469110,0.363837,...,NaN,NaN,NaN,NaN,NaN,21.151265,6.534020,NaN,NaN,0.050449
3,990025,UGC 8651 (DDO 181),0.555862,52.333293,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.912194,NaN,NaN,0.049394
4,990025,Tucana Dwarf,0.991196,81.802464,81033.956906,1.131163,13.800672,13.188907,0.910341,0.918353,...,NaN,NaN,NaN,NaN,NaN,NaN,5.611753,NaN,NaN,0.154247

In [5]:
data_test.head()

,galactic year,galaxy,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,...,Current health expenditure (% of GGP),"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII)
0,1007012,KK98 77,0.456086,51.562543,12236.576447,0.593325,10.414164,10.699072,0.547114,0.556267,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1007012,Reticulum III,0.529835,57.228262,3431.883825,0.675407,7.239485,5.311122,0.497688,0.409969,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1008016,Reticulum III,0.560976,59.379539,27562.914252,0.594624,11.774890,5.937797,0.544744,0.486167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1007012,Segue 1,0.565910,59.952390,20352.232905,0.837700,11.613621,10.067882,0.691641,0.523441,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1013042,Virgo I,0.588274,55.428320,23959.704016,0.520579,10.392416,6.374637,0.530676,0.580418,...,7.357729,0.583373,0.600445,0.856158,206.674424,224.104054,NaN,7.687626,NaN,NaN

## 3. Let's check the shape of the training and testing data, and have a view of the columns datatypes and names.

In [6]:
print(data_train.shape)
print(data_test.shape)

(3865, 80)
(890, 79)

In [7]:
dict(data_train.dtypes)

{'galactic year': dtype('int64'),
 'galaxy': dtype('O'),
 'existence expectancy index': dtype('float64'),
 'existence expectancy at birth': dtype('float64'),
 'Gross income per capita': dtype('float64'),
 'Income Index': dtype('float64'),
 'Expected years of education (galactic years)': dtype('float64'),
 'Mean years of education (galactic years)': dtype('float64'),
 'Intergalactic Development Index (IDI)': dtype('float64'),
 'Education Index': dtype('float64'),
 'Intergalactic Development Index (IDI), Rank': dtype('float64'),
 'Population using at least basic drinking-water services (%)': dtype('float64'),
 'Population using at least basic sanitation services (%)': dtype('float64'),
 'Gross capital formation (% of GGP)': dtype('float64'),
 'Population, total (millions)': dtype('float64'),
 'Population, urban (%)': dtype('float64'),
 'Mortality rate, under-five (per 1,000 live births)': dtype('float64'),
 'Mortality rate, infant (per 1,000 live births)': dtype('float64'),
 'Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64))': dtype('float64'),
 'Population, ages 15–64 (millions)': dtype('float64'),
 'Population, ages 65 and older (millions)': dtype('float64'),
 'Life expectancy at birth, male (galactic years)': dtype('float64'),
 'Life expectancy at birth, female (galactic years)': dtype('float64'),
 'Population, under age 5 (millions)': dtype('float64'),
 'Young age (0-14) dependency ratio (per 100 creatures ages 15-64)': dtype('float64'),
 'Adolescent birth rate (births per 1,000 female creatures ages 15-19)': dtype('float64'),
 'Total unemployment rate (female to male ratio)': dtype('float64'),
 'Vulnerable employment (% of total employment)': dtype('float64'),
 'Unemployment, total (% of labour force)': dtype('float64'),
 'Employment in agriculture (% of total employment)': dtype('float64'),
 'Labour force participation rate (% ages 15 and older)': dtype('float64'),
 'Labour force participation rate (% ages 15 and older), female': dtype('float64'),
 'Employment in services (% of total employment)': dtype('float64'),
 'Labour force participation rate (% ages 15 and older), male': dtype('float64'),
 'Employment to population ratio (% ages 15 and older)': dtype('float64'),
 'Jungle area (% of total land area)': dtype('float64'),
 'Share of employment in nonagriculture, female (% of total employment in nonagriculture)': dtype('float64'),
 'Youth unemployment rate (female to male ratio)': dtype('float64'),
 'Unemployment, youth (% ages 15–24)': dtype('float64'),
 'Mortality rate, female grown up (per 1,000 people)': dtype('float64'),
 'Mortality rate, male grown up (per 1,000 people)': dtype('float64'),
 'Infants lacking immunization, red hot disease (% of one-galactic year-olds)': dtype('float64'),
 'Infants lacking immunization, Combination Vaccine (% of one-galactic year-olds)': dtype('float64'),
 'Gross galactic product (GGP) per capita': dtype('float64'),
 'Gross galactic product (GGP), total': dtype('float64'),
 'Outer Galaxies direct investment, net inflows (% of GGP)': dtype('float64'),
 'Exports and imports (% of GGP)': dtype('float64'),
 'Share of seats in senate (% held by female)': dtype('float64'),
 'Natural resource depletion': dtype('float64'),
 'Mean years of education, female (galactic years)': dtype('float64'),
 'Mean years of education, male (galactic years)': dtype('float64'),
 'Expected years of education, female (galactic years)': dtype('float64'),
 'Expected years of education, male (galactic years)': dtype('float64'),
 'Maternal mortality ratio (deaths per 100,000 live births)': dtype('float64'),
 'Renewable energy consumption (% of total final energy consumption)': dtype('float64'),
 'Estimated gross galactic income per capita, male': dtype('float64'),
 'Estimated gross galactic income per capita, female': dtype('float64'),
 'Rural population with access to electricity (%)': dtype('float64'),
 'Domestic credit provided by financial sector (% of GGP)': dtype('float64'),
 'Population with at least some secondary education, female (% ages 25 and older)': dtype('float64'),
 'Population with at least some secondary education, male (% ages 25 and older)': dtype('float64'),
 'Gross fixed capital formation (% of GGP)': dtype('float64'),
 'Remittances, inflows (% of GGP)': dtype('float64'),
 'Population with at least some secondary education (% ages 25 and older)': dtype('float64'),
 'Intergalactic inbound tourists (thousands)': dtype('float64'),
 'Gross enrolment ratio, primary (% of primary under-age population)': dtype('float64'),
 'Respiratory disease incidence (per 100,000 people)': dtype('float64'),
 'Interstellar phone subscriptions (per 100 people)': dtype('float64'),
 'Interstellar Data Net users, total (% of population)': dtype('float64'),
 'Current health expenditure (% of GGP)': dtype('float64'),
 'Intergalactic Development Index (IDI), female': dtype('float64'),
 'Intergalactic Development Index (IDI), male': dtype('float64'),
 'Gender Development Index (GDI)': dtype('float64'),
 'Intergalactic Development Index (IDI), female, Rank': dtype('float64'),
 'Intergalactic Development Index (IDI), male, Rank': dtype('float64'),
 'Adjusted net savings ': dtype('float64'),
 'Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total': dtype('float64'),
 'Private galaxy capital flows (% of GGP)': dtype('float64'),
 'Gender Inequality Index (GII)': dtype('float64'),
 'y': dtype('float64')}

## 4. Let's see columns that doesn't contain null values. They are likely key features.

In [8]:
print(list(data_train.columns[data_train.isna().sum() == 0])) #prints columns with no null values
dict(data_train.isna().sum()) # a look at total null values in each column

['galactic year', 'galaxy', 'y']

{'galactic year': 0,
 'galaxy': 0,
 'existence expectancy index': 1,
 'existence expectancy at birth': 1,
 'Gross income per capita': 28,
 'Income Index': 28,
 'Expected years of education (galactic years)': 133,
 'Mean years of education (galactic years)': 363,
 'Intergalactic Development Index (IDI)': 391,
 'Education Index': 391,
 'Intergalactic Development Index (IDI), Rank': 433,
 'Population using at least basic drinking-water services (%)': 1844,
 'Population using at least basic sanitation services (%)': 1850,
 'Gross capital formation (% of GGP)': 2363,
 'Population, total (millions)': 2594,
 'Population, urban (%)': 2594,
 'Mortality rate, under-five (per 1,000 live births)': 2594,
 'Mortality rate, infant (per 1,000 live births)': 2606,
 'Old age dependency ratio (old age (65 and older) per 100 creatures (ages 15-64))': 2601,
 'Population, ages 15–64 (millions)': 2601,
 'Population, ages 65 and older (millions)': 2601,
 'Life expectancy at birth, male (galactic years)': 2601,
 'Life expectancy at birth, female (galactic years)': 2601,
 'Population, under age 5 (millions)': 2601,
 'Young age (0-14) dependency ratio (per 100 creatures ages 15-64)': 2601,
 'Adolescent birth rate (births per 1,000 female creatures ages 15-19)': 2613,
 'Total unemployment rate (female to male ratio)': 2628,
 'Vulnerable employment (% of total employment)': 2628,
 'Unemployment, total (% of labour force)': 2628,
 'Employment in agriculture (% of total employment)': 2628,
 'Labour force participation rate (% ages 15 and older)': 2628,
 'Labour force participation rate (% ages 15 and older), female': 2628,
 'Employment in services (% of total employment)': 2628,
 'Labour force participation rate (% ages 15 and older), male': 2628,
 'Employment to population ratio (% ages 15 and older)': 2628,
 'Jungle area (% of total land area)': 2631,
 'Share of employment in nonagriculture, female (% of total employment in nonagriculture)': 2628,
 'Youth unemployment rate (female to male ratio)': 2629,
 'Unemployment, youth (% ages 15–24)': 2629,
 'Mortality rate, female grown up (per 1,000 people)': 2612,
 'Mortality rate, male grown up (per 1,000 people)': 2612,
 'Infants lacking immunization, red hot disease (% of one-galactic year-olds)': 2646,
 'Infants lacking immunization, Combination Vaccine (% of one-galactic year-olds)': 2646,
 'Gross galactic product (GGP) per capita': 2663,
 'Gross galactic product (GGP), total': 2663,
 'Outer Galaxies direct investment, net inflows (% of GGP)': 2696,
 'Exports and imports (% of GGP)': 2721,
 'Share of seats in senate (% held by female)': 2742,
 'Natural resource depletion': 2733,
 'Mean years of education, female (galactic years)': 2725,
 'Mean years of education, male (galactic years)': 2727,
 'Expected years of education, female (galactic years)': 2756,
 'Expected years of education, male (galactic years)': 2757,
 'Maternal mortality ratio (deaths per 100,000 live births)': 2613,
 'Renewable energy consumption (% of total final energy consumption)': 2630,
 'Estimated gross galactic income per capita, male': 2810,
 'Estimated gross galactic income per capita, female': 2810,
 'Rural population with access to electricity (%)': 2836,
 'Domestic credit provided by financial sector (% of GGP)': 2786,
 'Population with at least some secondary education, female (% ages 25 and older)': 2776,
 'Population with at least some secondary education, male (% ages 25 and older)': 2778,
 'Gross fixed capital formation (% of GGP)': 2791,
 'Remittances, inflows (% of GGP)': 2837,
 'Population with at least some secondary education (% ages 25 and older)': 2814,
 'Intergalactic inbound tourists (thousands)': 2870,
 'Gross enrolment ratio, primary (% of primary under-age population)': 2827,
 'Respiratory disease incidence (per 100,000 people)': 2969,
 'Interstellar phone subscriptions (per 100 people)': 2974,
 'Interstellar Data Net users, total (% of population)': 2993,
 'Current health expenditure (% of GGP)': 2998,
 'Intergalactic Development Index (IDI), female': 2949,
 'Intergalactic Development Index (IDI), male': 2950,
 'Gender Development Index (GDI)': 2951,
 'Intergalactic Development Index (IDI), female, Rank': 2972,
 'Intergalactic Development Index (IDI), male, Rank': 2973,
 'Adjusted net savings ': 2953,
 'Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total': 2924,
 'Private galaxy capital flows (% of GGP)': 2991,
 'Gender Inequality Index (GII)': 3021,
 'y': 0}

## 5. Let's check the columns that when recorded have unique value for each observation. Probably, they are highly important features.

In [9]:
[i for i in data_train.columns if len(data_train[i].unique()) == data_train.shape[0]]

['existence expectancy index', 'existence expectancy at birth', 'y']

## 6. Let's check the number of unique galaxy and galactic year in the training and testing data.

In [10]:
print(len(data_train['galaxy'].unique()))
print(len(data_train['galactic year'].unique()))
print(len(data_test['galaxy'].unique()))
print(len(data_test['galactic year'].unique()))

181
26
172
10

## 7. Let's check if indeed for every galaxy in the training data, there is one unique galactic year per observation.

#### First, let's define a function that will group a dataset by a column_key and return a dictionary of column_key/dataframe pair.

In [11]:
def get_grouped_df(data, key):
    groups = data.groupby(key)
    dict_grp = {k: v for k, v in groups}
    return dict_grp

In [12]:
group1 = get_grouped_df(data_train, 'galaxy')
group1['Virgo I'].head()
#let's have a view of how each galaxy's mini dataframe looks like

,galactic year,galaxy,existence expectancy index,existence expectancy at birth,Gross income per capita,Income Index,Expected years of education (galactic years),Mean years of education (galactic years),Intergalactic Development Index (IDI),Education Index,...,"Intergalactic Development Index (IDI), female","Intergalactic Development Index (IDI), male",Gender Development Index (GDI),"Intergalactic Development Index (IDI), female, Rank","Intergalactic Development Index (IDI), male, Rank",Adjusted net savings,"Creature Immunodeficiency Disease prevalence, adult (% ages 15-49), total",Private galaxy capital flows (% of GGP),Gender Inequality Index (GII),y
2,990025,Virgo I,0.659443,59.570534,8441.707353,0.499762,8.840316,5.583973,0.469110,0.363837,...,NaN,NaN,NaN,NaN,NaN,21.151265,6.53402,NaN,NaN,0.050449
309,991020,Virgo I,0.555338,58.867426,24763.531222,0.463406,7.536744,2.763276,0.502295,0.342069,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.049411
364,992016,Virgo I,0.554174,60.551216,11439.589593,0.524210,7.485369,5.545963,0.430654,0.390630,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.049193
635,993012,Virgo I,0.612921,62.918772,24467.082523,0.481154,7.357494,5.868132,0.489407,0.348280,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.048858
897,994009,Virgo I,0.630974,50.942282,19221.268239,0.506944,7.312539,6.109797,0.412421,0.377290,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.048516

In [13]:
years_per_galaxy  = [len(group1[i]['galactic year']) 
                     for i in group1.keys()] #stores the number of galactic years per galaxy as a list

unique_years_per_galaxy  = [len(group1[i]['galactic year'].unique()) 
                            for i in group1.keys()] 
                            #stores the number of unique galactic years per galaxy as a list

In [14]:
unique_years_per_galaxy == years_per_galaxy #checks for equality

True

## 8. Similar to step 7 above, let's check if indeed for every galactic year in the training data, there is one unique galaxy per observation.

In [15]:
group2 = get_grouped_df(data_train, 'galactic year')

galaxies_per_year  = [len(group2[i]['galaxy']) for i in group2.keys()]
unique_galaxies_per_year  = [len(group2[i]['galaxy'].unique()) for i in group2.keys()]

In [16]:
galaxies_per_year == unique_galaxies_per_year

True

## 9. let's repeat steps 7 and 8  but this time with the testing data.

In [17]:
# similar to step 7
group3 =  get_grouped_df(data_test, 'galaxy')

years_per_galaxy_test  = [len(group3[i]['galactic year']) for i in group3.keys()]
unique_years_per_galaxy_test  = [len(group3[i]['galactic year'].unique()) for i in group3.keys()]

unique_years_per_galaxy_test == years_per_galaxy_test

True

In [18]:
# similar to step 8
group4 = get_grouped_df(data_test, 'galactic year')

galaxies_per_year_test  = [len(group4[i]['galaxy']) for i in group4.keys()]
unique_galaxies_per_year_test  = [len(group4[i]['galaxy'].unique()) for i in group4.keys()]

galaxies_per_year_test == unique_galaxies_per_year_test

True

## 10. Let's check the relationship between sampling of galactic years in the training and the testing data.

In [19]:
unique_gal_years_train = set(data_train['galactic year']) #unique galactic years in the training data
unique_gal_years_test = set(data_test['galactic year']) #unique galactic years in the testing data

print(sorted(list(unique_gal_years_train)), len(unique_gal_years_train))
print()
print(sorted(list(unique_gal_years_test)), len(unique_gal_years_test))

[990025, 991020, 992016, 993012, 994009, 995006, 996004, 997002, 998001, 999000, 1000000, 1001000, 1002001, 1003002, 1004004, 1005006, 1006009, 1007012, 1008016, 1009020, 1010025, 1011030, 1012036, 1013042, 1014049, 1015056] 26

[1007012, 1008016, 1009020, 1010025, 1011030, 1012036, 1013042, 1014049, 1015056, 1016064] 10

In [20]:
common_gal_years = unique_gal_years_train & unique_gal_years_test
print(common_gal_years, len(common_gal_years))
#checks for common galactic years between training and testing data.

{1014049, 1007012, 1012036, 1010025, 1008016, 1015056, 1013042, 1011030, 1009020} 9

#### It seems 9 of the 10 galactic years in the testing data are sampled in the training data.

#### Let's check the elapsed galactic year between two successive galactic years in the training data.

In [21]:
 print([sorted(list(unique_gal_years_train))[i+1] - sorted(list(unique_gal_years_train))[i] 
  for i in range(len(unique_gal_years_train) - 1)])

[995, 996, 996, 997, 997, 998, 998, 999, 999, 1000, 1000, 1001, 1001, 1002, 1002, 1003, 1003, 1004, 1004, 1005, 1005, 1006, 1006, 1007, 1007]

#### It seems the first observations in the training data were sampled after 995 galactic years. Subsequent elapsed galactic years of sampling was increase by one after two samplings.

## 11. Let's import useful libraries.

In [22]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn import tree
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor
from sklearn.base import BaseEstimator, RegressorMixin, TransformerMixin
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_error as mse
from scipy.optimize import minimize, Bounds, LinearConstraint
import math
import warnings
warnings.filterwarnings('ignore')

In [23]:
X_train, X_test, y_train, y_test = train_test_split(data_train, data_labels, test_size=0.2, random_state=0)

In [24]:
ran_f = ExtraTreesRegressor(bootstrap=True)

In [25]:
#grid = GridSearchCV(ran_f, {'n_estimators': range(10, 110, 10)}, cv=5, n_jobs=2, verbose=1)

In [26]:
model_pipe = Pipeline([('imp', SimpleImputer(strategy='median')), ('scaler', StandardScaler()), 
                       #('pca', PCA(n_components=10)), 
                       ('ran_f', ran_f)])

## 12. Let's build a custom model for predictions

#### This custom model will:
- split the training data into groups.
- split the testing data into groups.
- for each testing data group, train the corresponding training data group and then use it to predict the testing data group.
- for each testing data group, add the predicted labels as a new column in the group (minidf).
- join all testing groups together to form a new df.
- rearrange the predicted labels to correctly allign with their corresponding observations in the original testing data.

In [27]:
correlation = abs(data_train.copy().drop('y', axis=1).corrwith(data_labels))
columns = correlation.nlargest(20).index

In [28]:
class GalaxyModel(BaseEstimator, RegressorMixin):
    # this model is general purpose for grouping by and predicting any column, using any column as observation key, 
    #and for using any model.
    
    def __init__(self, key, label, ind, model): 
        self. key = key # key is the name of the column you want to groupby
        self.label = label # label is the name of the column we want to predict
        self.ind = ind # ind is the unique column in each mini df after grouping by key
        self.model = model # model is the model you want to use
        self.X_pred = []
        
    def fit(self, X_train, y_train=None):
# step1. split the training data into groups
        
        X = X_train.copy()
        self.train_mini_df = get_grouped_df(X, self.key) 
        
        return self
    
    def predict(self, X_test):
# step2. split the testing data into groups
        
        X = X_test.copy()
        self.test_mini_df = get_grouped_df(X, self.key)
        
# step3: 
# for each testing data group, train the corresponding training data group and then use it to predict the testing data group

        for key in self.test_mini_df:
            if key == 1016064: # uses galactic year 1015056 since 1016064 is not in testing data
                key = 1015056
                
            X_train = self.train_mini_df[key].copy().drop(self.key, axis=1)
            #drops key and ind columns of a copy training minidf
            
            y_label = np.array(X_train.pop(self.label)).reshape(-1, 1) # pops out label data as an array with 1 column
            
            self.model.fit(X_train, y_label) #fitting model on training data
            
            mini_X_test = self.test_mini_df[key].copy().drop(self.key, axis=1) 
            #drops key and ind columns of a copy testing minidf
            
            y_pred = self.model.predict(mini_X_test) #predicting testing data
            
#step4. for each testing data group, add the predicted labels as a new column in the group (minidf)
            self.test_mini_df[key][self.label] = y_pred 
            
# step5. join all testing groups together to form a new df
        pred_df = pd.concat([df for _, df in self.test_mini_df.items()])
        
# step6. creates a df consisting of three columns namely; galactic year, galaxy and predicted index
        pred_df = pred_df[['galactic year', 'galaxy', 'y']]
        
        
# step7. rearrange the predicted labels to correctly allign with their corresponding observations in the original testing data
        self.X_pred = X_test.copy().merge(pred_df, on=['galactic year', 'galaxy'], how='inner')
        
        return self.X_pred['y']

In [29]:
model = GalaxyModel('galaxy', 'y', 'galactic year', model_pipe)

In [30]:
model.fit(X_train)

GalaxyModel(ind='galactic year', key='galaxy', label='y',
            model=Pipeline(memory=None,
                           steps=[('imp',
                                   SimpleImputer(add_indicator=False, copy=True,
                                                 fill_value=None,
                                                 missing_values=nan,
                                                 strategy='median',
                                                 verbose=0)),
                                  ('scaler',
                                   StandardScaler(copy=True, with_mean=True,
                                                  with_std=True)),
                                  ('ran_f',
                                   ExtraTreesRegressor(bootstrap=True,
                                                       ccp_alpha=0.0,
                                                       criterion='mse',
                                                       max_depth=None,
                                                       max_features='auto',
                                                       max_leaf_nodes=None,
                                                       max_samples=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split=2,
                                                       min_weight_fraction_leaf=0.0,
                                                       n_estimators=100,
                                                       n_jobs=None,
                                                       oob_score=False,
                                                       random_state=None,
                                                       verbose=0,
                                                       warm_start=False))],
                           verbose=False))

In [31]:
y_pred = model.predict(X_test.drop('y', axis=1))

In [32]:
y_pred

0      0.045102
1      0.115325
2      0.048688
3      0.047861
4      0.165029
         ...
768    0.087669
769    0.061233
770    0.065016
771    0.053271
772    0.045011
Name: y, Length: 773, dtype: float64

In [33]:
mse(y_test, y_pred, squared=False)

0.01979915046088271

In [34]:
model.fit(data_train.copy(), data_labels)

GalaxyModel(ind='galactic year', key='galaxy', label='y',
            model=Pipeline(memory=None,
                           steps=[('imp',
                                   SimpleImputer(add_indicator=False, copy=True,
                                                 fill_value=None,
                                                 missing_values=nan,
                                                 strategy='median',
                                                 verbose=0)),
                                  ('scaler',
                                   StandardScaler(copy=True, with_mean=True,
                                                  with_std=True)),
                                  ('ran_f',
                                   ExtraTreesRegressor(bootstrap=True,
                                                       ccp_alpha=0.0,
                                                       criterion='mse',
                                                       max_depth=None,
                                                       max_features='auto',
                                                       max_leaf_nodes=None,
                                                       max_samples=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split=2,
                                                       min_weight_fraction_leaf=0.0,
                                                       n_estimators=100,
                                                       n_jobs=None,
                                                       oob_score=False,
                                                       random_state=None,
                                                       verbose=0,
                                                       warm_start=False))],
                           verbose=False))

In [35]:
y_pred = model.predict(data_test.copy())

## 13. Optimization Problem.

#### to minimize in scipy use the scipy.optimize.minimize library.

#### check out scipy.optimze.minimize function [here](https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html)

In [49]:
pot_for_inc = -np.log(y_pred + 0.01) + 3 # calculates potential for improvement in index

In [50]:
def likely_increase(X, p=pot_for_inc):
    return -sum(X * p**2 /1000) # calculates total likely increase in index. 
    #the minus sign is because we want to maximize the function since minimizing -a is same as maximizing a.

In [51]:
s_imp = SimpleImputer(strategy='median')

In [52]:
# drops the galaxy column since we can't imputation can't work with string
data_test_copy = data_test.copy().drop('galaxy', axis=1)
cols = data_test_copy.columns # store the columns names excluding that of galaxy.
data_test_copy = s_imp.fit_transform(data_test_copy) # imputates
data_test_copy = pd.DataFrame(data_test_copy, columns=cols) # converts to dataframe

# filters rows with existence expectancy index < 0.7
low_eei = data_test_copy[data_test_copy['existence expectancy index'] < 0.7]

In [53]:
data_test_copy2 = data_test_copy.sort_values(by='existence expectancy index') # sorts df by existence expectancy index

# check if original testing data set has top rows coresponding to rows with existence expectancy index < 0.7
sum(data_test_copy.loc[:len(low_eei) - 1, 'existence expectancy index'] == low_eei['existence expectancy index'])

66

In [54]:
boundary = Bounds([0]*890, [100]*890) # creates boundary constraint of 0 <= x <= 100
constraint1 = LinearConstraint([1]*890, [50000], [50000]) # creates constraint of sum(x) = 50,000

# create constraint of sum(extra energy of galaxies with existence expectancy index < 0.7) >= 10% 0f 50,000
constraint2 = LinearConstraint([1]*66 + [0]*824, [5000], [np.inf])

In [55]:
X0 = np.array([100]*66 + [52]*800 + [75]*24) # initial optimized extra energy guess

In [56]:
res = minimize(likely_increase, X0, constraints=[constraint1, constraint2],
               bounds=boundary, options={'verbose': 1, 'disp': True}) # optimizes
res.x

Iteration limit exceeded    (Exit mode 9)
            Current function value: -1755.8245248461646
            Iterations: 101
            Function evaluations: 90092
            Gradient evaluations: 101

array([1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 9.58551901e+01, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       9.92713440e+01, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02, 9.55597237e+01, 8.91602513e+01,
       8.70550718e+01, 7.33217981e+01, 6.56820042e+01, 1.00000000e+02,
       8.33248505e+01, 1.00000000e+02, 7.75444537e+01, 7.21982975e+01,
       1.00000000e+02, 7.79528800e+01, 9.03322106e+01, 1.00000000e+02,
       7.83610658e+01, 8.22211067e+01, 8.30286828e+01, 1.00000000e+02,
       1.00000000e+02, 8.70140956e+01, 9.14166968e+01, 8.06103106e+01,
       8.78557009e+01, 7.02169509e+01, 8.42298545e+01, 9.99614182e+01,
       9.32909658e+01, 9.80042608e+01, 8.37270059e+01, 7.12749751e+01,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       7.64664270e+01, 9.80750153e+01, 1.00000000e+02, 8.38061080e+01,
       8.31738185e+01, 8.39957954e+01, 1.00000000e+02, 1.00000000e+02,
       7.71618660e+01, 1.00000000e+02, 9.15946782e+01, 9.20849828e+01,
       1.00000000e+02, 8.42004341e+01, 6.82440188e+01, 1.00000000e+02,
       8.56731060e+01, 7.02253957e+01, 9.22402979e+01, 1.00000000e+02,
       7.49200880e+01, 7.87537355e+01, 1.00000000e+02, 1.00000000e+02,
       6.01110079e+01, 1.00000000e+02, 9.28725843e+01, 7.78192599e+01,
       1.00000000e+02, 7.36662692e+01, 1.00000000e+02, 6.72747167e+01,
       7.98173837e+01, 8.77011449e+01, 6.92954180e+01, 9.46250849e+01,
       1.00000000e+02, 7.43558217e+01, 1.00000000e+02, 6.71791483e+01,
       6.74468207e+01, 1.00000000e+02, 1.00000000e+02, 1.00000000e+02,
       8.21262516e+01, 7.56934849e+01, 7.53993946e+01, 1.00000000e+02,
       9.11394940e+01, 1.00000000e+02, 9.73008903e+01, 3.78279554e+01,
       8.77013479e+01, 1.00000000e+02, 7.61094889e+01, 8.56999692e+01,
       8.83421705e+01, 1.00000000e+02, 1.00000000e+02, 7.92852915e+01,
       9.84774944e+01, 6.65106649e+01, 9.95643991e+01, 1.00000000e+02,
       9.58628458e+01, 8.15321666e+01, 7.84670386e+01, 7.31315639e+01,
       7.51462273e+01, 8.26502989e+01, 1.00000000e+02, 8.26137335e+01,
       9.23546062e+01, 7.80669755e+01, 7.63385780e+01, 9.36830744e+01,
       9.73218845e+01, 8.38542557e+01, 1.00000000e+02, 9.08915933e+01,
       9.18328011e+01, 9.73307188e+01, 9.08943466e+01, 7.19608867e+01,
       7.02168984e+01, 1.00000000e+02, 9.27414349e+01, 8.38324479e+01,
       8.02027481e+01, 6.52858379e+01, 1.00000000e+02, 9.47611612e+01,
       8.28797494e+01, 7.43830993e+01, 1.00000000e+02, 9.02261730e+01,
       7.75607915e+01, 1.00000000e+02, 6.63450959e+01, 2.37831583e+01,
       6.91332002e+01, 9.29335322e+01, 1.00000000e+02, 9.67946050e+01,
       8.47372066e+01, 9.19402461e+01, 7.42496545e+01, 5.20909941e+01,
       9.99999760e+01, 1.00000000e+02, 1.00000000e+02, 8.63230880e+01,
       7.18577412e+01, 1.00000000e+02, 4.08960618e+01, 2.05614253e+01,
       6.11470337e+01, 8.14223248e+01, 4.17877472e+01, 7.76309615e+01,
       1.00000000e+02, 8.14119360e+01, 4.54137692e+01, 5.30973090e+01,
       8.03597816e+01, 8.74061847e+01, 1.00000000e+02, 7.29947675e+01,
       1.00000000e+02, 1.00000000e+02, 1.00000000e+02, 7.31356954e+01,
       6.23542726e+01, 9.54466490e+01, 8.72584666e+01, 1.00000000e+02,
       8.06241315e+01, 8.86072648e+01, 8.80656636e+01, 9.71494938e+01,
       7.55602771e+01, 9.27494204e+01, 7.75344833e+01, 4.16432682e+01,
       8.87673075e+01, 8.28837431e+01, 8.43458130e+01, 9.47364617e+01,
       6.71681246e+01, 1.25795412e+01, 6.78174666e+01, 9.07634344e+01,
       8.15361008e+01, 1.00000000e+02, 7.98454094e+01, 9.95356079e+01,
       1.00000000e+02, 8.19413090e+01, 7.42327662e+01, 9.63728453e+01,
       1.00000000e+02, 7.19905248e+01, 3.68405728e+01, 7.11283762e+01,
       7.84973277e+01, 5.55488060e+01, 7.06250811e+01, 8.43717386e+01,
       8.27392408e+01, 9.99845706e+01, 8.21303954e+01, 6.87393526e+01,
       8.23624372e+01, 4.80836921e+01, 3.66162133e+01, 8.72869839e+01,
       6.75668982e+01, 7.75169472e+01, 1.00000000e+02, 8.30297841e+01,
       6.32655177e+01, 8.56877488e+01, 8.17799894e+01, 7.94347112e+01,
       8.05037958e+01, 2.55063503e+01, 7.55421417e+01, 7.28728621e+01,
       6.63338107e+01, 9.34248611e+01, 8.23486773e+01, 7.07285170e+01,
       9.96753448e+01, 8.28737494e+01, 7.35070726e+01, 1.00000000e+02,
       5.69147202e+01, 8.30079773e+01, 8.31323706e+01, 8.28920913e+01,
       7.23751502e+01, 6.60937187e+01, 1.00000000e+02, 9.99982414e+01,
       5.72626836e+01, 7.80754817e+01, 2.79003790e+01, 7.16704237e+01,
       4.18312707e+01, 8.22139754e+01, 4.42108922e+01, 1.00000000e+02,
       8.59634870e+01, 9.09254871e+01, 8.90061643e+01, 8.94351956e+01,
       1.00000000e+02, 7.47703777e+01, 5.51545835e+01, 7.60699106e+00,
       7.30332302e+01, 1.35138033e+01, 9.48748423e+01, 1.00000000e+02,
       8.60769643e+01, 7.65659944e+01, 8.02003765e+01, 7.35610861e+01,
       7.10124578e+01, 6.57213960e+01, 8.42108277e+01, 6.56642561e+01,
       1.92681865e+01, 6.12570349e+01, 9.91521664e+01, 6.18974428e+01,
       6.56811960e+01, 6.98339553e+01, 1.00000000e+02, 2.19166342e+01,
       6.13924108e+01, 7.29915190e+01, 7.43333702e+01, 8.42112386e+01,
       1.00000000e+02, 5.25576132e+01, 8.63373251e+01, 8.50127923e+01,
       5.43404323e+01, 1.51487895e+01, 5.33878547e+01, 6.75224928e+01,
       5.46101208e+01, 5.64435532e+01, 6.78124400e+01, 1.38290725e+01,
       8.18414334e+01, 7.36928426e+01, 7.56840813e+01, 5.00560019e+01,
       7.70494025e+01, 6.13882427e+01, 7.00812232e+01, 8.06150744e+01,
       7.42317770e+01, 8.13922029e+01, 7.47145892e+01, 2.02066264e+01,
       6.11324919e+01, 4.60715702e+01, 2.87077259e+01, 7.11037935e+01,
       4.57884732e+01, 1.48127126e+01, 3.79470994e+01, 7.47646285e+01,
       4.86111963e+01, 5.58183264e+01, 9.11811590e+01, 5.32409688e+01,
       2.32759518e+01, 6.29900651e+01, 9.21911409e+01, 7.47501246e+01,
       9.36731874e+01, 7.26215137e+01, 8.31713740e+01, 3.14142018e+01,
       5.06515681e-10, 9.07485005e+01, 4.08776680e+01, 1.50665633e+00,
       3.28797386e+01, 8.69825180e+00, 1.00000000e+02, 8.03705888e+01,
       1.00000000e+02, 5.00277308e+01, 3.98061070e+01, 7.35464539e+01,
       6.55168778e+01, 8.19618496e+01, 9.01097481e+01, 6.35001819e+01,
       8.92749116e+01, 5.90321569e+01, 7.33888562e+01, 6.72617928e+01,
       4.99500221e+01, 4.61775601e+01, 7.79515190e+01, 6.14322759e+01,
       8.86346929e+01, 2.49998400e+01, 4.16565901e+01, 5.97943450e+01,
       4.08339404e+01, 7.20969424e+01, 5.25676233e+01, 4.91053461e+01,
       6.37798880e+01, 7.86051882e+01, 8.68604461e+01, 5.06242838e+01,
       7.97969045e+01, 6.29880734e+01, 8.80858972e+01, 9.24582523e+01,
       1.70991498e+01, 9.05936697e+01, 6.73166100e+01, 4.38212399e+01,
       9.03459821e+01, 6.83030394e+01, 1.00000000e+02, 7.80588676e+01,
       5.01876005e-10, 6.28992196e+01, 6.88561951e+01, 7.08661537e+01,
       3.39366303e+01, 5.63276461e+01, 6.97968984e+01, 7.00821277e+01,
       5.56637351e+01, 6.35071290e+01, 1.00000000e+02, 1.43586734e+01,
       6.02382220e+01, 8.34368806e+01, 6.09674204e+01, 4.01879928e+01,
       5.63437370e+01, 6.27094953e+01, 5.87253565e+01, 3.64303870e+01,
       7.91342361e+01, 6.87273237e+01, 8.88613316e+01, 4.16776101e+01,
       1.43513230e+01, 4.68264116e+01, 6.18156503e+01, 5.04449931e-10,
       5.38490177e-10, 3.80805939e+01, 7.98399003e+01, 6.74227115e+01,
       3.31082203e+01, 4.68648922e+01, 4.13851287e+01, 1.00000000e+02,
       5.83533661e+01, 3.30156045e+01, 7.19800913e+01, 2.08999353e+01,
       5.63413168e+01, 1.83407141e+01, 1.00000000e+02, 4.78899898e+01,
       7.27331615e-01, 6.77890392e+01, 6.31592943e+01, 3.79255790e+01,
       7.26216471e+01, 6.27293836e+01, 6.76947204e+01, 1.17630501e+01,
       5.63403312e+01, 8.07073866e+00, 6.33798020e+01, 6.14290815e+01,
       5.35185692e-10, 5.64464966e+01, 9.51641503e+01, 2.72604089e+00,
       1.50865031e+01, 5.73881165e+01, 7.76749401e+01, 7.00150633e+00,
       5.04616339e-10, 2.36711568e+01, 5.56370336e+01, 5.66631958e+01,
       6.47609324e+01, 7.70078481e+01, 6.80948155e+01, 6.61792243e+01,
       1.43577283e+01, 5.83775296e+01, 4.59962417e+01, 5.44862460e+01,
       4.72638712e+01, 1.00000000e+02, 4.32367852e+00, 5.79172477e+01,
       6.08647394e+01, 8.13876061e+01, 4.12623909e+01, 6.69848717e+01,
       3.65810136e+01, 3.78094564e+01, 1.00000000e+02, 4.11478140e+01,
       8.02245377e+01, 6.83525375e+01, 5.63320562e+01, 4.06755925e+01,
       5.16296965e-10, 4.60714853e+01, 7.07673410e+01, 7.90526050e+01,
       7.32406158e+01, 1.73379720e-02, 6.49433277e+01, 5.01096620e-10,
       5.90208181e+01, 8.96820044e+01, 7.79410291e+01, 8.12396160e+01,
       8.07548174e+01, 3.80795086e+00, 6.52429843e+01, 3.99997435e+01,
       5.49918628e+01, 4.15589984e+01, 5.33575528e+01, 7.84998837e+01,
       3.04734939e+01, 7.24915126e+01, 3.83340323e+01, 5.04692292e-10,
       4.14470428e+01, 9.77005491e+01, 4.45226644e+00, 5.09253376e-10,
       3.66212820e+01, 5.83087011e+01, 9.83509805e+01, 1.44947591e+01,
       2.18361546e+01, 6.63368438e+01, 8.79123893e+01, 2.65359114e+00,
       6.11624759e+01, 2.00721731e+01, 6.28788579e+01, 3.70877446e+01,
       1.15346533e+01, 1.47301975e+01, 6.89232846e+01, 6.91881366e+01,
       4.87393221e+01, 4.40998135e+01, 5.32287444e-10, 7.13403977e+01,
       7.54392013e+01, 3.23638387e+01, 9.11534239e+01, 1.73278233e-02,
       7.13464319e+01, 6.24943328e+01, 6.08979469e+01, 5.69650119e-10,
       8.09882137e+01, 4.33035960e+01, 5.04727505e-10, 7.94275693e+01,
       6.34338700e+01, 5.79243603e+01, 5.47333103e+01, 2.19795867e+01,
       3.23235706e+01, 7.98041783e+01, 5.15166332e-10, 7.98090361e+01,
       6.79779088e+01, 4.62527982e+01, 2.84881701e+01, 1.19582287e+01,
       5.28525394e-10, 5.03883471e-10, 4.62498004e+01, 9.09476741e+01,
       6.02111657e+01, 5.39964980e-10, 7.66078290e+01, 5.47689265e+01,
       2.18329611e+01, 9.51508315e+01, 4.64957808e-01, 5.07850643e-10,
       5.16619997e+01, 4.31479781e+01, 4.73488553e+00, 5.13723625e+00,
       5.16426631e-10, 4.69029639e+01, 9.14272361e+01, 5.18230032e-10,
       1.47047076e+01, 6.06352936e+01, 4.21000314e+01, 3.52664402e+01,
       3.98576222e+01, 8.46758466e+01, 2.90021400e+01, 4.32670187e+01,
       4.59916266e+01, 4.67666329e+01, 1.32910598e+01, 4.66168528e+01,
       5.64478046e+01, 7.52778202e+01, 3.99268865e+01, 1.21814504e+01,
       5.70252492e+00, 6.34226126e+01, 6.87984979e+01, 5.05904829e-10,
       2.50292867e+00, 2.29083993e+01, 7.79500268e+01, 5.78354469e+00,
       4.75681053e+01, 2.23619356e+01, 1.12659933e+01, 6.01715840e+01,
       6.64970400e+01, 7.44661053e+01, 3.97886609e+01, 5.18905897e-10,
       8.34301852e+01, 5.14776753e-10, 6.03372165e+01, 5.15707781e+01,
       8.04522454e+01, 2.81915139e+01, 8.20947400e+01, 1.50206459e+01,
       5.41079710e-10, 5.16179769e-10, 5.36845634e+01, 5.28245448e-10,
       5.58281026e+01, 1.86502454e+01, 8.51570925e+01, 5.32377236e-10,
       4.65263068e+01, 2.04192675e+01, 4.33249280e+01, 4.92021979e-10,
       5.64976112e+01, 4.05098957e+01, 7.88632783e+01, 5.20976714e-10,
       5.04566340e-10, 7.79925103e+01, 3.47129479e+01, 9.91300963e+01,
       5.56757778e+01, 7.24586929e+01, 3.69212605e+01, 5.38608835e-10,
       5.01099593e-10, 7.10218587e+01, 3.01001048e+01, 5.14668190e-10,
       6.53106786e+01, 1.23514806e+01, 4.83080284e+01, 5.98999173e+01,
       5.37099038e+01, 1.12734760e+01, 8.91841623e+01, 3.27820830e+01,
       1.38148151e+01, 6.43908929e+01, 3.43510486e+01, 5.39629651e-10,
       6.20582411e+01, 1.51505739e+01, 5.16652839e-10, 5.28334131e-10,
       3.27383274e+01, 5.41568037e-10, 4.75352567e+01, 3.29633953e+01,
       1.23582736e+01, 5.40847248e-10, 2.95433077e+01, 5.10080606e-10,
       5.06395879e-10, 3.91189686e+01, 5.32754187e-10, 5.06944025e-10,
       4.33234104e+01, 4.23573321e+01, 6.25166562e+01, 2.42349756e+01,
       3.79549264e+01, 5.42006303e-10, 3.87866302e+01, 6.12888250e+01,
       4.27411919e+01, 5.17631371e-10, 7.29300989e+01, 9.88551589e+01,
       6.06714481e+01, 3.81987562e+01, 5.67501485e-10, 6.51311822e+01,
       5.35159604e-10, 6.50149373e+01, 5.38083930e-10, 4.94719117e+01,
       4.33063775e+01, 9.48155026e-01, 5.14260270e-10, 5.40944314e-10,
       5.20618852e-10, 5.64627293e+01, 5.46705068e+01, 1.50986782e+01,
       1.10129142e+01, 5.39125251e-10, 9.86379882e+01, 5.14318351e-10,
       5.16631033e+01, 7.44974938e+01, 5.15342248e-10, 5.29571052e-10,
       5.15623273e-10, 4.61992571e+01, 5.67516494e+01, 2.27729109e+01,
       5.15341303e-10, 5.13519360e+00, 4.32596081e+01, 5.17958493e-10,
       5.28301414e-10, 1.96907920e+01, 5.10071098e-10, 6.94326036e+01,
       5.14722895e-10, 5.18945709e-10, 5.04583600e+01, 5.03328945e-10,
       5.16771454e-10, 5.34083956e-10, 5.15896028e-10, 5.16341543e-10,
       5.40865595e-10, 5.00783511e-10, 5.09479067e-10, 6.46273003e+01,
       2.84843875e+01, 5.09161676e-10, 4.62547122e+01, 5.39769374e-10,
       5.64590059e+01, 5.41007935e-10, 5.15273299e-10, 5.39979060e-10,
       6.58024354e+01, 4.60730530e+01, 5.15032727e-10, 5.13812666e-10,
       5.15040381e-10, 5.35166621e-10, 6.09784434e+01, 5.15333900e-10,
       5.15522810e-10, 8.38658379e-01, 5.30494738e-10, 3.27816793e+01,
       5.31778078e-10, 5.30567479e-10, 5.21438651e-10, 5.30585451e-10,
       5.62983423e-10, 5.44816815e-10, 5.04305064e-10, 4.89031517e+01,
       5.15370948e-10, 5.39800939e-10, 5.29247020e-10, 5.16568741e-10,
       5.44425724e-10, 5.40992457e-10, 3.97854588e+01, 5.04865830e-10,
       5.16050774e-10, 1.37820952e+00, 5.17030693e-10, 5.35111648e-10,
       6.04817346e+01, 1.17996421e+01, 4.15381914e+01, 5.15204099e-10,
       5.17954327e-10, 5.36157649e-10, 5.41681106e-10, 5.17209243e-10,
       5.14482262e-10, 5.17774732e-10, 5.42469774e-10, 5.33110972e-10,
       5.20896315e-10, 5.18267453e-10, 5.27501144e-10, 5.15415691e-10,
       5.11558390e-10, 5.61073645e+01, 5.15224473e-10, 5.20274329e-10,
       5.62942349e-10, 5.33320511e-10, 6.86525676e+01, 5.22410672e-10,
       5.20432519e-10, 5.33140888e-10, 5.32022704e-10, 5.18192481e-10,
       9.84018443e+01, 5.27441984e-10, 5.39638902e-10, 5.20486619e-10,
       2.55147455e+01, 5.37819568e-10, 5.15533418e-10, 5.40834547e-10,
       5.39219535e-10, 5.36155608e-10, 5.40923246e-10, 5.37921888e-10,
       3.28645328e+01, 5.17153089e-10, 5.33241563e-10, 5.16011314e-10,
       5.17530955e-10, 5.16467969e-10, 5.15110846e-10, 5.36775271e-10,
       5.13224075e-10, 5.39811681e-10, 7.11975818e+01, 7.29439149e-10,
       7.46142710e-10, 7.31031759e-10, 7.30591886e-10, 7.31896059e-10,
       5.86842795e+00, 7.60572231e-10, 7.43238298e-10, 5.89096697e+00,
       7.26344683e-10, 7.42986257e-10, 7.47065106e-10, 7.38498722e-10,
       7.29230914e-10, 7.41175025e-10, 1.16863332e-02, 7.52196831e-10,
       7.32878132e-10, 9.66362387e+01, 7.80189962e+01, 5.53684778e+01,
       6.64076496e+01, 9.98811220e+01])

In [57]:
opt_pred = res.x # stores optimal extra energy
-res.fun # checks maximum sum of likely increase in index

1755.8245248461646

In [58]:
sum(opt_pred)

49999.99999999999

In [59]:
solution1 = pd.DataFrame({'Index': data_test.index, 'pred': y_pred, 'opt_pred': opt_pred}) # stores solution as df
solution1

     Index      pred    opt_pred
0        0  0.043579  100.000000
1        1  0.048941  100.000000
2        2  0.042988  100.000000
3        3  0.039534  100.000000
4        4  0.025611  100.000000
..     ...       ...         ...
885    885  0.047134   96.636239
886    886  0.058690   78.018996
887    887  0.076699   55.368478
888    888  0.067322   66.407650
889    889  0.045355   99.881122

[890 rows x 3 columns]

In [60]:
solution1.to_csv('./Documents/prohack_dataset/solution1.csv') # stores solution to disk as csv file to be submitted!